import { LlmAnalysis, AnalysisBlock, AnalysisBlockUtils, EvidenceLink } from './blocks';
import { RefactorBundleFacts } from '../../facts/types';

/**
 * Resolve evidence JSON path to file location
 */
export function resolveEvidencePath(
  evidencePath: string,
  facts: RefactorBundleFacts
): { filePath: string; lineNumber?: number; description: string } | null {
  // Parse JSON path like "findings.incompleteness.missing[0]"
  const pathParts = evidencePath.split('.');
  const arrayMatch = pathParts[pathParts.length - 1].match(/^(\w+)\[(\d+)\]$/);

  if (arrayMatch) {
    const [_, arrayName, index] = arrayMatch;
    const arrayPath = pathParts.slice(0, -1).join('.');

    // Navigate to the array in facts
    let current: any = facts;
    for (const part of arrayPath.split('.')) {
      current = current[part];
      if (!current) return null;
    }

    const item = current[parseInt(index)];
    if (item && item.symbol_id) {
      const filePath = item.symbol_id.split(':')[0];
      // Try to extract line number from location data
      let lineNumber: number | undefined;
      if (item.loc_pre?.start?.line) {
        lineNumber = item.loc_pre.start.line;
      } else if (item.loc_post?.start?.line) {
        lineNumber = item.loc_post.start.line;
      } else if (item.expected?.lastPath) {
        // Try to get from expected state
        lineNumber = undefined;
      }

      return {
        filePath,
        lineNumber,
        description: evidencePath
      };
    }

    // Also check evidence object directly
    if (facts.evidence && facts.evidence[arrayName]) {
      const evidenceArray = facts.evidence[arrayName];
      if (Array.isArray(evidenceArray) && evidenceArray[parseInt(index)]) {
        const evidenceItem = evidenceArray[parseInt(index)];
        if (evidenceItem.symbol_id) {
          const filePath = evidenceItem.symbol_id.split(':')[0];
          return {
            filePath,
            lineNumber: evidenceItem.loc_pre?.start?.line || evidenceItem.loc_post?.start?.line,
            description: evidencePath
          };
        }
      }
    }
  }

  // Try direct path access (e.g., "bundle.shas")
  let current: any = facts;
  for (const part of evidencePath.split('.')) {
    if (current && typeof current === 'object') {
      current = current[part];
    } else {
      return null;
    }
  }

  // If we found something but it's not a symbol, return path info
  if (current !== undefined && current !== null) {
    return {
      filePath: evidencePath, // Use path as file path for non-symbol evidence
      description: evidencePath
    };
  }

  return null;
}

/**
 * Renderer for LLM analysis results
 * Generates interwoven markdown with clickable evidence links
 */
export class AnalysisRenderer {

  /**
   * Render complete analysis to markdown
   */
  renderAnalysis(analysis: LlmAnalysis, facts: RefactorBundleFacts): string {
    let markdown = this.renderHeader(analysis, facts);

    // Sort blocks by type priority
    const sortedBlocks = this.sortBlocks(analysis.blocks);

    for (const block of sortedBlocks) {
      markdown += this.renderBlock(block, facts);
    }

    markdown += this.renderFooter(analysis);
    return markdown;
  }

  /**
   * Render analysis header
   */
  private renderHeader(analysis: LlmAnalysis, facts: RefactorBundleFacts): string {
    let header = `# 🤖 LLM Analysis Report\n\n`;
    header += `**Generated:** ${new Date(analysis.metadata.timestamp).toLocaleString()}\n`;
    header += `**Bundle:** ${facts.bundle.shas.length} commits (${facts.bundle.oldestSha.substring(0, 8)}...)\n`;
    header += `**Symbols:** ${facts.working.symbols} analyzed, ${facts.working.edges} relationships\n`;
    header += `**Model:** ${analysis.metadata.model}\n`;
    header += `**Analysis Time:** ${this.formatDuration(analysis.metadata.totalCalls)}\n\n`;

    if (analysis.summary) {
      header += `## 📋 Executive Summary\n\n${analysis.summary}\n\n`;
    }

    return header;
  }

  /**
   * Render analysis footer
   */
  private renderFooter(analysis: LlmAnalysis): string {
    let footer = `---\n\n`;
    footer += `**Analysis Details:** ${analysis.metadata.totalCalls} LLM calls, `;
    footer += `~${analysis.metadata.totalTokens.toLocaleString()} tokens\n`;
    footer += `*Generated by Git Context v2 LLM Analyst*\n`;

    return footer;
  }

  /**
   * Sort blocks by priority and type
   */
  private sortBlocks(blocks: AnalysisBlock[]): AnalysisBlock[] {
    const typePriority = { intent: 0, discovery: 1, drift: 2, cleanup: 3, summary: 4 };

    return blocks.sort((a, b) => {
      const typeDiff = typePriority[a.type] - typePriority[b.type];
      if (typeDiff !== 0) return typeDiff;

      // Within same type, sort by confidence
      return b.confidence - a.confidence;
    });
  }

  /**
   * Render a single analysis block
   */
  private renderBlock(block: AnalysisBlock, facts: RefactorBundleFacts): string {
    const icon = this.getBlockIcon(block.type);
    let content = `## ${icon} ${block.title}\n\n`;

    if (block.claims.length > 0) {
      content += this.renderClaims(block.claims, facts);
    }

    if (block.actions.length > 0) {
      content += this.renderActions(block.actions, facts);
    }

    // Add confidence indicator
    if (block.confidence < 0.8) {
      content += `\n⚠️ **Low Confidence:** This analysis has ${(block.confidence * 100).toFixed(0)}% confidence. Verify manually.\n`;
    }

    content += `\n`;
    return content;
  }

  /**
   * Get icon for block type
   */
  private getBlockIcon(type: AnalysisBlock['type']): string {
    switch (type) {
      case 'intent': return '🎯';
      case 'discovery': return '💡';
      case 'drift': return '🔍';
      case 'cleanup': return '🧹';
      case 'summary': return '📊';
      default: return '📝';
    }
  }

  /**
   * Render claims section
   */
  private renderClaims(claims: any[], facts: RefactorBundleFacts): string {
    let content = `### Findings\n\n`;

    for (const claim of claims) {
      const severityIcon = this.getSeverityIcon(claim.severity);
      content += `- ${severityIcon} **${claim.severity.toUpperCase()}:** ${claim.text}\n`;

      if (claim.confidence < 0.9) {
        content += `  *(confidence: ${(claim.confidence * 100).toFixed(0)}%)*\n`;
      }

      // Render evidence links
      if (claim.evidence && claim.evidence.length > 0) {
        content += `  **Evidence:**\n`;
        for (const evidence of claim.evidence) {
          content += `  - ${this.renderEvidenceLink(evidence, facts)}\n`;
        }
      }

      content += `\n`;
    }

    return content;
  }

  /**
   * Render actions section
   */
  private renderActions(actions: any[], facts: RefactorBundleFacts): string {
    let content = `### Recommended Actions\n\n`;

    // Sort actions by priority
    const sortedActions = AnalysisBlockUtils.sortActions(actions);

    for (const action of sortedActions) {
      const priorityIcon = this.getPriorityIcon(action.priority);
      const riskIcon = this.getRiskIcon(action.risk);

      content += `- ${priorityIcon} **[${action.priority.toUpperCase()}]** `;
      content += `[${action.effort.toUpperCase()}] ${action.description}\n`;

      if (action.risk !== 'low') {
        content += `  ${riskIcon} **Risk:** ${action.risk}\n`;
      }

      // Show dependencies
      if (action.dependsOn && action.dependsOn.length > 0) {
        content += `  ⏳ **Depends on:** ${action.dependsOn.join(', ')}\n`;
      }

      // Render evidence links
      if (action.evidence && action.evidence.length > 0) {
        content += `  **Evidence:**\n`;
        for (const evidence of action.evidence) {
          content += `  - ${this.renderEvidenceLink(evidence, facts)}\n`;
        }
      }

      content += `\n`;
    }

    return content;
  }

  /**
   * Render evidence link with clickable reference
   */
  private renderEvidenceLink(evidence: EvidenceLink, facts: RefactorBundleFacts): string {
    // Create a clickable link format that triggers the openEvidence command
    // Format: [description](command:git-context.openEvidence?encodedArgs)

    const args = {
      path: evidence.path,
      description: evidence.description,
      filePath: evidence.filePath,
      lineNumber: evidence.lineNumber,
      symbolId: evidence.symbolId
    };

    // If we have symbolId but no filePath, try to resolve it
    if (!args.filePath && args.symbolId) {
      args.filePath = AnalysisBlockUtils.extractFilePath(args.symbolId);
    }

    // VS Code command URIs require arguments to be a JSON array, URI encoded
    const encodedArgs = encodeURIComponent(JSON.stringify([args]));
    const linkText = evidence.description;

    // Add file/symbol info if available for display text
    let extraInfo = '';
    if (evidence.filePath) {
      extraInfo += ` in ${evidence.filePath}`;
      if (evidence.lineNumber) {
        extraInfo += `:${evidence.lineNumber}`;
      }
    } else if (evidence.symbolId) {
      const filePath = AnalysisBlockUtils.extractFilePath(evidence.symbolId);
      const symbolName = AnalysisBlockUtils.extractSymbolName(evidence.symbolId);
      extraInfo += ` ${symbolName} in ${filePath}`;
    }

    // Try to resolve count from facts
    const count = this.resolveEvidenceCount(evidence.path, facts);
    if (count !== null) {
      extraInfo += ` (${count} items)`;
    }

    return `[${linkText}${extraInfo}](command:git-context.openEvidence?${encodedArgs})`;
  }

  /**
   * Resolve evidence count from facts JSON path
   */
  private resolveEvidenceCount(path: string, facts: RefactorBundleFacts): number | null {
    try {
      const parts = path.split('.');
      let current: any = facts;

      for (const part of parts) {
        if (part.includes('[')) {
          // Handle array access like findings.incompleteness.missing
          const arrayMatch = part.match(/^([^[]+)/);
          if (arrayMatch) {
            current = current[arrayMatch[1]];
          }
        } else {
          current = current[part];
        }
      }

      if (Array.isArray(current)) {
        return current.length;
      } else if (typeof current === 'number') {
        return current;
      }
    } catch (error) {
      // Ignore errors in path resolution
    }

    return null;
  }

  /**
   * Get severity icon
   */
  private getSeverityIcon(severity: string): string {
    switch (severity) {
      case 'critical': return '🚨';
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  }

  /**
   * Get priority icon
   */
  private getPriorityIcon(priority: string): string {
    switch (priority) {
      case 'urgent': return '🚨';
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  }

  /**
   * Get risk icon
   */
  private getRiskIcon(risk: string): string {
    switch (risk) {
      case 'high': return '⚠️';
      case 'medium': return '⚡';
      case 'low': return '✅';
      default: return '❓';
    }
  }

  /**
   * Format duration (placeholder for now)
   */
  private formatDuration(callCount: number): string {
    // This is a placeholder - in a real implementation we'd track actual timing
    return `~${callCount * 30}s`;
  }

  /**
   * Generate quick stats summary
   */
  static generateQuickStats(analysis: LlmAnalysis, facts: RefactorBundleFacts): string {
    const totalActions = analysis.blocks.reduce((sum, block) => sum + block.actions.length, 0);
    const highPriorityActions = analysis.blocks.reduce((sum, block) =>
      sum + block.actions.filter(a => a.priority === 'high' || a.priority === 'urgent').length, 0);

    let stats = `📊 **Analysis Results:** `;
    stats += `${analysis.blocks.length} analysis sections, `;
    stats += `${totalActions} actions recommended`;

    if (highPriorityActions > 0) {
      stats += ` (${highPriorityActions} high priority)`;
    }

    return stats;
  }
}
